version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: r-d-telegram-game-postgres
    environment:
      POSTGRES_DB: telegram_game
      POSTGRES_USER: telegram_user
      POSTGRES_PASSWORD: telegram_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telegram_user -d telegram_game"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - telegram_game_network

  redis:
    image: redis:7-alpine
    container_name: r-d-telegram-game-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - telegram_game_network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: r-d-telegram-game-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - telegram_game_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  telegram_game_network:
    driver: bridge
