"""add_quest_proposal_and_reputation_tables

Revision ID: 90dc64ca001e
Revises: cd3f491d571f
Create Date: 2025-09-11 20:59:34.755740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90dc64ca001e'
down_revision = 'cd3f491d571f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_reputation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('faction', sa.String(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_player_reputation_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_reputation'))
    )
    op.create_index(op.f('ix_player_reputation_id'), 'player_reputation', ['id'], unique=False)
    op.create_table('quest_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('questgiver_name', sa.String(), nullable=False),
    sa.Column('quest_intro', sa.Text(), nullable=False),
    sa.Column('quest_description', sa.Text(), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('faction', sa.String(), nullable=True),
    sa.Column('reward_gold', sa.Integer(), nullable=True),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Integer(), nullable=True),
    sa.Column('info_asked', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quest_proposals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quest_proposals'))
    )
    op.create_index(op.f('ix_quest_proposals_id'), 'quest_proposals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quest_proposals_id'), table_name='quest_proposals')
    op.drop_table('quest_proposals')
    op.drop_index(op.f('ix_player_reputation_id'), table_name='player_reputation')
    op.drop_table('player_reputation')
    # ### end Alembic commands ###
