"""add_character_attributes_and_progression

Revision ID: c030eb610a8e
Revises: 1b97bcc51f24
Create Date: 2025-09-05 09:35:09.837664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c030eb610a8e'
down_revision = '1b97bcc51f24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('luck', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('available_stat_points', sa.Integer(), nullable=False))
    op.alter_column('players', 'character_class',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'character_class',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('players', 'available_stat_points')
    op.drop_column('players', 'luck')
    # ### end Alembic commands ###
