"""add_world_and_progress_system

Revision ID: cd3f491d571f
Revises: c030eb610a8e
Create Date: 2025-09-05 09:58:49.585856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3f491d571f'
down_revision = 'c030eb610a8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create player_progress table
    op.create_table('player_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('total_experience', sa.Integer(), nullable=False),
    sa.Column('completed_quests', sa.JSON(), nullable=True),
    sa.Column('unlocked_regions', sa.JSON(), nullable=True),
    sa.Column('visited_locations', sa.JSON(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_player_progress_id'), 'player_progress', ['id'], unique=False)
    
    # Create exploration_sessions table
    op.create_table('exploration_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('session_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('events_encountered', sa.JSON(), nullable=True),
    sa.Column('enemies_defeated', sa.JSON(), nullable=True),
    sa.Column('loot_obtained', sa.JSON(), nullable=True),
    sa.Column('experience_gained', sa.Integer(), nullable=True),
    sa.Column('gold_gained', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exploration_sessions_id'), 'exploration_sessions', ['id'], unique=False)
    
    # Create region_unlocks table
    op.create_table('region_unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('unlock_type', sa.String(), nullable=False),
    sa.Column('unlock_value', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_unlocked_by_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id')
    )
    op.create_index(op.f('ix_region_unlocks_id'), 'region_unlocks', ['id'], unique=False)
    
    # Create player_stats table
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_enemies_defeated', sa.Integer(), nullable=True),
    sa.Column('total_quests_completed', sa.Integer(), nullable=True),
    sa.Column('total_regions_explored', sa.Integer(), nullable=True),
    sa.Column('total_exploration_time', sa.Integer(), nullable=True),
    sa.Column('favorite_region', sa.String(), nullable=True),
    sa.Column('longest_exploration_session', sa.Integer(), nullable=True),
    sa.Column('total_gold_earned', sa.Integer(), nullable=True),
    sa.Column('total_experience_gained', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_region_unlocks_id'), table_name='region_unlocks')
    op.drop_table('region_unlocks')
    op.drop_index(op.f('ix_exploration_sessions_id'), table_name='exploration_sessions')
    op.drop_table('exploration_sessions')
    op.drop_index(op.f('ix_player_progress_id'), table_name='player_progress')
    op.drop_table('player_progress')
    # ### end Alembic commands ###
